import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../../../shared/api/client';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { DataTable } from '../../../shared/ui/DataTable';
import { useActiveCompany } from '../../../shared/company/useActiveCompany';
import type { PagedResult } from '../../../shared/api/types';

interface NotificationDto {
  id: string;
  title: string;
  body: string;
  isRead: boolean;
  createdAt: string;
  deliveryStatus: string;
}

/**
 * In-app notification read side (Phase M7, 2026-07-15) — the Notification
 * entity was fully dormant before this phase (no repository, no CQRS, no UI).
 * External delivery via SendGrid (Phase M7 remaining, 2026-07-16) now runs as
 * a background dispatcher, polling for anything not yet Sent and emailing the
 * recipient — the "Delivery" column below surfaces that status read-only;
 * there is no retry/resend button here since the dispatcher already retries
 * Failed deliveries automatically on its own next poll.
 */
export function NotificationsPage() {
  const { companyId } = useActiveCompany();
  const queryClient = useQueryClient();
  const [unreadOnly, setUnreadOnly] = useState(false);

  const notificationsQuery = useQuery({
    queryKey: ['notifications', companyId, unreadOnly],
    queryFn: () => apiClient.get<PagedResult<NotificationDto>>(`/core/notifications?companyId=${companyId}&unreadOnly=${unreadOnly}&page=1&pageSize=50`),
    enabled: Boolean(companyId),
  });

  const markRead = useMutation({
    mutationFn: (id: string) => apiClient.post<NotificationDto>(`/core/notifications/${id}/mark-read?companyId=${companyId}`, {}),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['notifications', companyId] }),
  });

  if (!companyId) return null;

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="mb-1 text-xl font-semibold text-text">Notifications</h1>
          <p className="text-sm text-text-muted">In-app notifications, generated by the Approvals workflow and delivered by email via SendGrid.</p>
        </div>
        <label className="flex items-center gap-2 text-sm text-text-muted">
          <input type="checkbox" checked={unreadOnly} onChange={(e) => setUnreadOnly(e.target.checked)} />
          Unread only
        </label>
      </div>

      <Card>
        <DataTable
          columns={[
            { header: 'Title', render: (n: NotificationDto) => n.title },
            { header: 'Body', render: (n: NotificationDto) => n.body },
            { header: 'Received', render: (n: NotificationDto) => new Date(n.createdAt).toLocaleString() },
            { header: 'Delivery', render: (n: NotificationDto) => n.deliveryStatus },
            {
              header: '',
              render: (n: NotificationDto) =>
                n.isRead ? (
                  <span className="text-xs text-text-muted">Read</span>
                ) : (
                  <Button variant="secondary" onClick={() => markRead.mutate(n.id)} disabled={markRead.isPending}>
                    Mark read
                  </Button>
                ),
            },
          ]}
          rows={notificationsQuery.data?.data}
          isLoading={notificationsQuery.isLoading}
          emptyMessage="No notifications yet."
          rowKey={(n) => n.id}
        />
      </Card>
    </div>
  );
}
