namespace FusionOS.Modules.Core.Application.Auth;

/// <summary>
/// The single source of truth for every permission code enforced anywhere in
/// FusionOS via IRequirePermission (07_SECURITY.md §2). New modules add their
/// codes here so GetOrCreateCompanyOwnerRoleAsync can seed them - otherwise a
/// freshly-bootstrapped company's "Owner" role would silently be missing grants
/// for whatever was added after the role was first created.
///
/// The "*.read" codes were added in the 2026-07-14 sprint audit remediation:
/// previously 0 of 17 query handlers in the whole repo implemented IRequirePermission,
/// so any authenticated user in a tenant could read all of that tenant's data
/// regardless of role. "core.role.manage" was added alongside the RBAC
/// administration feature (create roles, edit their permissions, assign users)
/// that makes those read/write gates mean something beyond the single
/// auto-granted "Owner" role. Because GetOrCreateCompanyOwnerRoleAsync grants
/// every code in this catalog to the Owner role, adding new codes here is
/// enough for existing Owners to keep working with no data migration required.
///
/// The ".update"/".deactivate" codes were added in the Phase H2/I mechanical
/// sweep (2026-07-14): every entity that previously had a dead GetById stub
/// (always returning NotFound) now has a real GetById, an Update command, and
/// a soft Deactivate command (never a hard delete) - see
/// docs/REMEDIATION_ROADMAP.md Phase I.
/// </summary>
public static class PermissionCatalog
{
    public static readonly IReadOnlyList<(string Module, string Code, string Description)> All = new (string, string, string)[]
    {
        ("core", "core.role.manage", "Create roles, edit their permissions, and assign users to roles"),
        ("core", "core.user.register", "Register (invite) a new user into this company"),
        ("core", "core.company.read", "View a company's own details"),
        ("core", "core.company.update", "Rename/update a company's own details"),
        ("core", "core.company.deactivate", "Deactivate a company"),
        ("core", "core.audit.read", "View the company's audit log"),
        ("core", "core.settings.read", "View the company's settings"),
        ("core", "core.settings.update", "Update the company's settings"),
        ("core", "core.approval-request.create", "Submit a new approval request"),
        ("core", "core.approval-request.decide", "Approve or reject a pending approval step"),
        ("core", "core.approval-request.read", "View approval requests"),
        ("core", "core.notification.read", "View your own in-app notifications"),
        ("finance", "finance.account.create", "Create a chart-of-accounts account"),
        ("finance", "finance.account.read", "View chart-of-accounts accounts"),
        ("finance", "finance.account.update", "Update a chart-of-accounts account"),
        ("finance", "finance.account.deactivate", "Deactivate a chart-of-accounts account"),
        ("finance", "finance.journal-entry.create", "Create a draft journal entry"),
        ("finance", "finance.journal-entry.post", "Post a journal entry to the ledger"),
        ("finance", "finance.journal-entry.read", "View journal entries"),
        ("finance", "finance.receivable.read", "View accounts-receivable ledger entries and balances"),
        ("finance", "finance.receivable.record-payment", "Record a customer payment against an invoice"),
        ("finance", "finance.payable.read", "View accounts-payable ledger entries and balances"),
        ("finance", "finance.payable.record-charge", "Record a bill charge owed to a supplier"),
        ("finance", "finance.payable.record-payment", "Record a payment made to a supplier"),
        ("finance", "finance.cost-center.create", "Create a cost center"),
        ("finance", "finance.cost-center.read", "View cost centers"),
        ("finance", "finance.cost-center.update", "Update a cost center"),
        ("finance", "finance.cost-center.deactivate", "Deactivate a cost center"),
        ("finance", "finance.tax-jurisdiction.create", "Create a tax jurisdiction"),
        ("finance", "finance.tax-jurisdiction.read", "View tax jurisdictions"),
        ("finance", "finance.tax-jurisdiction.update", "Update a tax jurisdiction"),
        ("finance", "finance.tax-jurisdiction.deactivate", "Deactivate a tax jurisdiction"),
        ("finance", "finance.tax-rate.create", "Create a tax rate within a jurisdiction"),
        ("finance", "finance.tax-rate.read", "View tax rates"),
        ("finance", "finance.tax-rate.update", "Update a tax rate"),
        ("finance", "finance.tax-rate.deactivate", "Deactivate a tax rate"),
        ("finance", "finance.bank-account.create", "Create a bank account"),
        ("finance", "finance.bank-account.read", "View bank accounts"),
        ("finance", "finance.bank-account.update", "Update a bank account"),
        ("finance", "finance.bank-account.deactivate", "Deactivate a bank account"),
        ("finance", "finance.bank-statement-line.create", "Record a bank statement line"),
        ("finance", "finance.bank-statement-line.read", "View bank statement lines and reconciliation summaries"),
        ("finance", "finance.bank-statement-line.reconcile", "Reconcile or unreconcile a bank statement line"),
        ("finance", "finance.exchange-rate.create", "Create a dated exchange rate for a currency pair"),
        ("finance", "finance.exchange-rate.read", "View exchange rates and convert an amount between currencies"),
        ("finance", "finance.exchange-rate.update", "Correct an exchange rate's rate/effective date"),
        ("finance", "finance.exchange-rate.deactivate", "Deactivate an exchange rate"),
        ("finance", "finance.budget.create", "Create a budget"),
        ("finance", "finance.budget.read", "View budgets and their actual-vs-budget report"),
        ("finance", "finance.budget.update", "Update a budget"),
        ("finance", "finance.budget.deactivate", "Deactivate a budget"),
        ("finance", "finance.budget-line.create", "Create a budget line"),
        ("finance", "finance.budget-line.read", "View budget lines"),
        ("finance", "finance.budget-line.update", "Update a budget line's amount"),
        ("finance", "finance.fixed-asset.create", "Register a fixed asset"),
        ("finance", "finance.fixed-asset.read", "View fixed assets and their calculated depreciation schedule"),
        ("finance", "finance.fixed-asset.update", "Update a fixed asset's name/cost center"),
        ("finance", "finance.fixed-asset.deactivate", "Deactivate a fixed asset"),
        ("finance", "finance.fixed-asset.dispose", "Record a fixed asset as disposed"),
        ("inventory", "inventory.product.create", "Create a product"),
        ("inventory", "inventory.product.read", "View products"),
        ("inventory", "inventory.product.update", "Edit a product"),
        ("inventory", "inventory.product.deactivate", "Deactivate a product"),
        ("inventory", "inventory.stock.adjust", "Adjust stock-on-hand"),
        ("inventory", "inventory.stock.read", "View stock-on-hand and ledger entries"),
        ("inventory", "inventory.costing.read", "View inventory costing/valuation (weighted-average)"),
        ("procurement", "procurement.purchase-order.approve", "Approve a purchase order"),
        ("procurement", "procurement.purchase-order.create", "Create a purchase order"),
        ("procurement", "procurement.purchase-order.read", "View purchase orders"),
        ("procurement", "procurement.rfq.award", "Award an RFQ to a supplier's quote"),
        ("procurement", "procurement.rfq.convert", "Convert an awarded RFQ into a purchase order"),
        ("procurement", "procurement.rfq.create", "Create an RFQ"),
        ("procurement", "procurement.rfq.read", "View RFQs"),
        ("procurement", "procurement.rfq.send", "Send an RFQ to suppliers"),
        ("procurement", "procurement.rfq.submit-quote", "Submit a supplier quote against an RFQ"),
        ("procurement", "procurement.supplier.create", "Create a supplier"),
        ("procurement", "procurement.supplier.read", "View suppliers"),
        ("procurement", "procurement.supplier.update", "Update a supplier"),
        ("procurement", "procurement.supplier.deactivate", "Deactivate a supplier"),
        ("procurement", "procurement.supplier-scorecard.read", "View supplier performance scorecards"),
        ("procurement", "procurement.contract.create", "Create a supplier contract"),
        ("procurement", "procurement.contract.read", "View supplier contracts"),
        ("procurement", "procurement.contract.terminate", "Terminate a supplier contract"),
        ("sales", "sales.customer.create", "Create a customer"),
        ("sales", "sales.customer.read", "View customers"),
        ("sales", "sales.customer.update", "Update a customer"),
        ("sales", "sales.customer.deactivate", "Deactivate a customer"),
        ("sales", "sales.customer.assign-price-list", "Assign or clear a customer's price list"),
        ("sales", "sales.credit-note.create", "Create a credit note"),
        ("sales", "sales.credit-note.issue", "Issue a credit note"),
        ("sales", "sales.credit-note.read", "View credit notes"),
        ("sales", "sales.dispatch.create", "Create a dispatch"),
        ("sales", "sales.dispatch.read", "View dispatches"),
        ("sales", "sales.invoice.create", "Create a sales invoice"),
        ("sales", "sales.invoice.issue", "Issue a sales invoice"),
        ("sales", "sales.invoice.read", "View sales invoices"),
        ("sales", "sales.price-list.create", "Create a price list"),
        ("sales", "sales.price-list.read", "View price lists"),
        ("sales", "sales.quotation.accept", "Accept a quotation"),
        ("sales", "sales.quotation.convert", "Convert an accepted quotation into a sales order"),
        ("sales", "sales.quotation.create", "Create a quotation"),
        ("sales", "sales.quotation.read", "View quotations"),
        ("sales", "sales.quotation.reject", "Reject a quotation"),
        ("sales", "sales.sales-order.confirm", "Confirm a sales order"),
        ("sales", "sales.sales-order.create", "Create a sales order"),
        ("sales", "sales.sales-order.read", "View sales orders"),
        ("sales", "sales.commission-rate.set", "Set a salesperson's commission rate"),
        ("sales", "sales.commission-rate.read", "View salesperson commission rates"),
        ("sales", "sales.commission-report.read", "View the commission summary report"),
        ("warehouse", "warehouse.goods-receipt.create", "Create a goods receipt"),
        ("warehouse", "warehouse.goods-receipt.read", "View goods receipts"),
        ("warehouse", "warehouse.goods-receipt.suggest-putaway", "Suggest a putaway bin for a goods receipt line"),
        ("warehouse", "warehouse.goods-receipt.confirm-putaway", "Confirm the putaway bin for a goods receipt line"),
        ("warehouse", "warehouse.warehouse.create", "Create a warehouse"),
        ("warehouse", "warehouse.warehouse.read", "View warehouses"),
        ("warehouse", "warehouse.warehouse.update", "Edit a warehouse"),
        ("warehouse", "warehouse.warehouse.deactivate", "Deactivate a warehouse"),
        ("warehouse", "warehouse.zone.create", "Create a warehouse zone"),
        ("warehouse", "warehouse.zone.read", "View warehouse zones"),
        ("warehouse", "warehouse.zone.update", "Edit a warehouse zone"),
        ("warehouse", "warehouse.zone.deactivate", "Deactivate a warehouse zone"),
        ("warehouse", "warehouse.bin.create", "Create a bin within a zone"),
        ("warehouse", "warehouse.bin.read", "View bins"),
        ("warehouse", "warehouse.bin.update", "Edit a bin"),
        ("warehouse", "warehouse.bin.deactivate", "Deactivate a bin"),
        ("warehouse", "warehouse.cycle-count.create", "Start a cycle count"),
        ("warehouse", "warehouse.cycle-count.record", "Record the counted quantity for a pending cycle count"),
        ("warehouse", "warehouse.cycle-count.read", "View cycle counts"),
        ("warehouse", "warehouse.pick-list.create", "Create a pick list for a sales order"),
        ("warehouse", "warehouse.pick-list.assign", "Assign a pick list to a user"),
        ("warehouse", "warehouse.pick-list.record", "Record picked quantities on a pick list"),
        ("warehouse", "warehouse.pick-list.pack", "Confirm a fully-picked pick list as packed"),
        ("warehouse", "warehouse.pick-list.read", "View pick lists"),
        ("manufacturing", "manufacturing.bill-of-materials.create", "Define a bill of materials for a manufactured product"),
        ("manufacturing", "manufacturing.bill-of-materials.read", "View bills of materials"),
        ("manufacturing", "manufacturing.bill-of-materials.deactivate", "Deactivate a bill of materials"),
        ("manufacturing", "manufacturing.work-order.create", "Create a work order from a bill of materials"),
        ("manufacturing", "manufacturing.work-order.release", "Release a draft work order to the floor"),
        ("manufacturing", "manufacturing.work-order.complete", "Complete a work order (consumes components, produces the product)"),
        ("manufacturing", "manufacturing.work-order.read", "View work orders"),
        ("crm", "crm.lead.create", "Capture a new lead"),
        ("crm", "crm.lead.qualify", "Qualify a lead"),
        ("crm", "crm.lead.disqualify", "Disqualify a lead"),
        ("crm", "crm.lead.read", "View leads"),
        ("crm", "crm.opportunity.create", "Open an opportunity from a qualified lead"),
        ("crm", "crm.opportunity.win", "Mark an opportunity won (creates a Sales customer)"),
        ("crm", "crm.opportunity.lose", "Mark an opportunity lost"),
        ("crm", "crm.opportunity.read", "View opportunities"),
        ("quality", "quality.inspection.create", "Open a quality inspection"),
        ("quality", "quality.inspection.record", "Record an inspection's pass/fail results"),
        ("quality", "quality.inspection.read", "View quality inspections"),
        ("maintenance", "maintenance.asset.create", "Register a machine/asset"),
        ("maintenance", "maintenance.asset.deactivate", "Deactivate a machine/asset"),
        ("maintenance", "maintenance.asset.read", "View machines/assets"),
        ("maintenance", "maintenance.request.create", "Log a preventive or breakdown maintenance request"),
        ("maintenance", "maintenance.request.start", "Start work on a maintenance request"),
        ("maintenance", "maintenance.request.complete", "Complete a maintenance request"),
        ("maintenance", "maintenance.request.read", "View maintenance requests"),
        ("hrms", "hrms.employee.create", "Create an employee record"),
        ("hrms", "hrms.employee.deactivate", "Deactivate an employee record"),
        ("hrms", "hrms.employee.read", "View employee records"),
        ("hrms", "hrms.leave-request.create", "Submit a leave request"),
        ("hrms", "hrms.leave-request.approve", "Approve a leave request"),
        ("hrms", "hrms.leave-request.reject", "Reject a leave request"),
        ("hrms", "hrms.leave-request.read", "View leave requests"),
        ("bi", "bi.kpi-definition.create", "Define a KPI"),
        ("bi", "bi.kpi-definition.deactivate", "Deactivate a KPI"),
        ("bi", "bi.kpi-definition.read", "View KPI definitions"),
        ("bi", "bi.kpi-snapshot.record", "Record a KPI value"),
        ("bi", "bi.kpi-snapshot.read", "View recorded KPI values"),
        ("ai", "ai.recommendation.record", "Record an AI recommendation"),
        ("ai", "ai.recommendation.accept", "Accept an AI recommendation"),
        ("ai", "ai.recommendation.dismiss", "Dismiss an AI recommendation"),
        ("ai", "ai.recommendation.read", "View AI recommendations"),
        ("marketplace", "marketplace.plugin-listing.create", "Add a plugin/theme/pack listing to the catalog"),
        ("marketplace", "marketplace.plugin-listing.deactivate", "Delist a plugin/theme/pack"),
        ("marketplace", "marketplace.plugin-listing.read", "View the plugin catalog"),
        ("marketplace", "marketplace.plugin-installation.install", "Install a catalog listing"),
        ("marketplace", "marketplace.plugin-installation.disable", "Disable an installed plugin"),
        ("marketplace", "marketplace.plugin-installation.enable", "Re-enable a disabled plugin"),
        ("marketplace", "marketplace.plugin-installation.uninstall", "Uninstall a plugin"),
        ("marketplace", "marketplace.plugin-installation.read", "View installed plugins"),
    };
}
